services:

  Gateway:
    build:
      content: .
      dockerfile: gateway/Dockerfile

      container_name: Gateway

      ports: 
        - "8000:8000"

      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_started

      env_file:
        - gateway/.env

      network: 
        - insertion-remote

  
  llm:
    build:
      context: .
      dockerfile: llm/Dockerfile

      container_name: llm

      env_file:
        - llm/.env

      network: 
        - insertion-remote


  Temporal:
    image: temporalio/auto-setup:latest

    container_name: temporal

    depends_on:
      - temporal-postgres

    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: Temporal
      POSTGRES_PWD: Temporal
      POSTGRES_SEEDS: TemporalPostgres

    ports:
      - "7233:7233"

    networks:
      - insertion-remote


  # Temporal's own persistence DB
  TemporalPostgres:
    image: postgres:17

    container_name: temporal-postgres

    environment:
      POSTGRES_USER: Temporal
      POSTGRES_PASSWORD: Temporal
      POSTGRES_DB: Temporal

    volumes:
      - temporal_postgres_data:/var/lib/postgresql/data

    networks:
      - backend


  TemporalUI:
    image: temporalio/ui:latest

    container_name: TemporalUI

    depends_on:
      - temporal

    environment:
      TEMPORAL_ADDRESS: temporal:7233

    ports:
      - "8080:8080"

    networks:
      - insertion-remote


  MasterWorker:
    build:
      context: .
      dockerfile: orchestration/master/Dockerfile

    container_name: MasterWorker

    depends_on:
      - temporal
      - llm

    networks:
      - insertion-remote


  Initializer:
    build:
      context: .
      dockerfile: apps/initializer/Dockerfile

      container_name: Initializer

    env_file:
      - apps/initializer/.env

    networks:
      - insertion-remote


  Postgres:
    image: postgres:17

    container_name: Postgres

    environment:
      POSTGRES_DB: insertion
      POSTGRES_USER: insertion
      POSTGRES_PASSWORD: insertion

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U insertion -d insertion"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - insertion-remote


  Redis:
    image: redis:8

    container_name: Redis

    networks:
      - insertion-remote



volumes:

  postgres_data:

  temporal_postgres_data:



networks:

  insertion-remote:
    driver: bridge