services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    volumes:
      - ./app:/app/app

    networks:
      - experimentos-network


  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: experimentos
      POSTGRES_USER: experimentos
      POSTGRES_PASSWORD: experimentos

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U experimentos -d experimentos"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - experimentos-network


  redis:
    image: redis:8

    ports:
      - "6379:6379"

    networks:
      - experimentos-network



volumes:
  postgres_data:


networks:
  experimentos-network:
    driver: bridge