GREENHOUSE_COMPANIES = [

    # AI
    "openai",
    "anthropic",
    "perplexity",
    "scaleai",
    "mistralai",
    "cohere",
    "runway",
    "twelve-labs",

    # Infrastructure / Cloud
    "databricks",
    "confluent",
    "cockroachlabs",
    "planetlabs",
    "snowflake",
    "elastic",
    "hashicorp",

    # Developer Tools
    "notion",
    "linear",
    "plaid",
    "rippling",
    "render",
    "flyio",
    "supabase",
    "railway",
    "temporal",
    "pulumi",

    # Security
    "wiz",
    "snyk",
    "chainguard",
    "teleport",

    # Fintech
    "brex",
    "mercury",
    "ramp",

    # AI Infra
    "modal",
    "togetherai",
    "baseten",
    "groq",

    # India
    "sarvam",
    "krutrim",
    "yellowai",
    "observeai",
    "atlan",
    "browserstack",
    "chargebee",
    "whatfix",
    "moengage",
    "clevertap",
    "postman",
    "innovaccer",
    "sigNoz",
    "last9",
]

LEVER_COMPANIES = [

    # Global
    # "figma",
    # "mongodb",
    # "sourcegraph",
    # "posthog",
    # "vanta",
    # "convex",
    # "retool",
    # "grafana",
    # "airbyte",
    # "airtable",
    # "clerk",
    # "warp",
    # "replit",
    # "loom",
    # "calendly",
    # "checkr",
    # "pilot",
    # "persona",
    # "benchling",
    # "hex",
    # "dbt",
    # "launchdarkly",
    # "coder",
    # "prefect",
    # "dagster",
    # "dagshub",
    # "humanloop",

    # India / Indian startups
    "devrev",
    "hasura",
    "appsmith",
    "hoppscotch",
    "porter",
    "facets",
    "middleware",
    "infracloud",
    "cashfree",
    "slice",
    "fi",
    "groww",
    "razorpay",
    "jupiter",
    "open",
    "navi",
    "meesho",
    "zepto",
    "healthplix",
    "ekacare",
]